---
title: "tidy_data"
output: github_document
---
 
```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

## pivot longer

what about `gather()`...? never use this one, always use `pivot_longer()`)

Load the PULSE data

```{r}
pulse_df = 
  read_sas("data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
```

Let's try to pivot

```{r}
pulse_tidy = 
  pulse_df %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_", 
    values_to = "bdi"
  ) %>%
  mutate(
    visit = replace(visit, visit == "bl", "00m"), 
    visit = factor("visit")
  )
```

## pivot_wider

what about `spread()`...? never use this one, always use `pivot_wider()`)

make up a results data table

```{r}
analysis_df = 
  tibble(
    group = c("treatment", "treatment", "control", "control"),
    time = c("a", "b", "a", "b"),
    group_mean = c(4, 8, 3, 6)
  )
```

```{r}
analysis_df %>%
  pivot_wider(
    names_from = "time",
    values_from = "group_mean"
  ) %>%
  knitr::kable()
```


## bind_rows

what about `rbind()`...? never use this one, always use `bind_rows()`)

import the LotR words

```{r}
fellowship_df = 
  read_excel("data/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_rings")
```

```{r}
two_towers_df = 
  read_excel("data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")
```

```{r}
return_df = 
  read_excel("data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")
```

```{r}
lotr_df = 
  bind_rows(fellowship_df, two_towers_df, return_df) %>%
  janitor::clean_names() %>%
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words"
  ) %>%
  relocate(movie) %>%
  mutate(race =  str_to_lower(race))
```


## joins

Look at FAS data. This imports and clean litters and pups data

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  separate(group, into = c("dose", "day_of_tx"), 3) %>%
  relocate(litter_number) %>%
  mutate(dose = str_to_lower(dose))

pups_df = 
  read_csv("data/FAS_pups.csv") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female"))
```


Let's join this up

```{r}
fas_df = 
  left_join(pups_df, litters_df, by = "litter_number") %>%
  relocate(litter_number, dose, day_of_tx)
```




